### ISSUE TITLE
401 

### ISSUE THREAD

**Issue by fontexD** [RunnerM/simply-dns-webhook#66]
![apiwork](https://github.com/RunnerM/simply-dns-webhook/assets/87015443/3ff5330d-0240-4e53-9620-a0e4fc195914)
ime="2023-12-18T13:51:41Z" level=info msg="Cleaning up challenge for: _acme-challenge.markus.fontex.dk."
time="2023-12-18T13:51:41Z" level=debug msg="Loading config..."
time="2023-12-18T13:51:41Z" level=debug msg="Config loaded successfully."
time="2023-12-18T13:51:41Z" level=debug msg="Loading API credentials from secret: simply-auth"
time="2023-12-18T13:51:41Z" level=error msg="Failed request, response code:  401"
time="2023-12-18T13:51:41Z" level=debug msg="Record(0) fetched for cleanup."
time="2023-12-18T13:51:41Z" level=error msg="Failed request, response code:  401"
time="2023-12-18T13:51:41Z" level=error msg="record(0) have not been cleaned up"
time="2023-12-18T13:51:43Z" level=info msg="Presenting challenge for: _acme-challenge.markus.fontex.dk."
time="2023-12-18T13:51:43Z" level=error msg="Failed request, response code:  401"
time="2023-12-18T13:51:43Z" level=error msg="Failed request, response:  401"
time="2023-12-18T13:51:43Z" level=debug msg="Challenge have been created with record id: 0"

webhook version
image: ghcr.io/runnerm/simply-dns-webhook:v1.4.3

cert-manager version
image: quay.io/jetstack/cert-manager-controller:v1.13.3

K8s: 
v1.28.1

ive tested the cred with curl and it works fine so the auth and api is ok , ive attached a picture that shows auth and api works .

**Comment by RunnerM** [comment]
Can you please check your secret, if it is properly converted to base64/retrieved from encrypted store? Some base64 converters tend to add an end of line at the end.

**Comment by fontexD** [comment]
yeah, just verified with https://www.base64decode.org/
took the base64 string and convert it, no spaces or wierd endings i tried both using https://www.base64decode.org/
and in terminal echo "value" | base64 

i normally always use echo "value" | base64 so im sure there is nothing wierd inside the string

**Comment by fontexD** [comment]
i tried to copy down the go code and build a image where it would fmt.println(accoutname) (apikey) just to see in terminal what it actually tries to send but it wouldt let me buld it for some reason 

Dockerfile:16
--------------------
  14 |     COPY . .
  15 |
  16 | >>> RUN CGO_ENABLED=0 go build -o webhook -ldflags '-w -extldflags "-static"' .
  17 |
  18 |     FROM alpine:3.16
--------------------
ERROR: failed to solve: process "/bin/sh -c CGO_ENABLED=0 go build -o webhook -ldflags '-w -extldflags \"-static\"' ." did not complete successfully: exit code: 1

Keep getting this output :/

im not actually a progammer but i do some go lang coding for hobby/fun, my primary work is data-technican infrastrcuture and cka certified ^_^

**Comment by RunnerM** [comment]
I will try to recreate the issue then. 😉

**Comment by fontexD** [comment]
E1218 16:38:56.319946       1 sync.go:190] "cert-manager/challenges: propagation check failed" err="DNS record for \"markus.fontex.dk\" not yet propagated" resource_name="markuscert-3-698267038-3968477047" resource_namespace="markus" resource_kind="Challenge" resource_version="v1" dnsName="markus.fontex.dk" type="DNS-01"

**Comment by RunnerM** [comment]
It works for me from secret and from config too, try with config setup first maybe. Bumped the test version to 1.28.

**Comment by RunnerM** [comment]
I will close this issue soon if there isn't anything to discuss. :)

**Comment by fontexD** [comment]
I tried everything just can't get it to work so wierd,I really can't see what the issue is, tryed encoding the bas64 in so many ways now also creating the secret in all the possible ways I know of 

Is there any other way I could create the config with the id/pass beside using a secret?

**Comment by RunnerM** [comment]
Yepp as I suggested before and it is in the README as well you can do this to test if you credentials are valid if you modify the main config: 

```diff
-              secretName: simply-credentials # notice the name
+              accountName: "<account-name>"
+              apiKey: "<api-key>"
```

Of course after validation I would suggest to sort the secret out and use that instead.

**Comment by fontexD** [comment]
man, all working now .. a big error40 from my side

4get to add the -n flag when i did the base64 ...... xD
sorry for taking so much of your time when it was a matter of typo so to say ...

thanks for an amazing app :=) ! now i can close my 80 on my proxy and use dns-solver instead ^_^!

**Comment by fontexD** [comment]
man, all working now .. a big error40 from my side

4get to add the -n flag when i did the base64 ...... xD
sorry for taking so much of your time when it was a matter of typo so to say ...

thanks for an amazing app :=) ! now i can close my 80 on my proxy and use dns-solver instead ^_^!
