### ISSUE TITLE
[Feature Request] Multi platform support.

### ISSUE THREAD

**Issue by marklonquist** [RunnerM/simply-dns-webhook#68]
Any plans on making a version that works with aarch64? I'm setting up a Raspberry Pi 5 home cluster :)

**Comment by RunnerM** [comment]
I will take a look at multi arch tags when I have time. 😉

Probably next release I will include it. You should be able to rebuild the image for yourself to ARM.

**Comment by marklonquist** [comment]
yea i'll do a build myself to target ARM :) just nice to have the repo/image owner handle it for updates etc :D

**Comment by RunnerM** [comment]
Will do. 🙂

**Comment by RunnerM** [comment]
Will be merged with new cert-manager version bump at the end of the month. :)

**Comment by marklonquist** [comment]
nice :D
